// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Survivor.Data;

#nullable disable

namespace Survivor.Data.Migrations
{
    [DbContext(typeof(SurvivorDbContext))]
    [Migration("20241224103005_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Survivor.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6821),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6830),
                            Name = "Ünlüler"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6832),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6832),
                            Name = "Gönüllüler"
                        });
                });

            modelBuilder.Entity("Survivor.Entities.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6896),
                            FirstName = "Acun",
                            IsDeleted = false,
                            LastName = "Ilıcalı",
                            ModifiedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6897)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6898),
                            FirstName = "Aleyna",
                            IsDeleted = false,
                            LastName = "Avcı",
                            ModifiedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6898)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6899),
                            FirstName = "Hadise",
                            IsDeleted = false,
                            LastName = "Açıkgöz",
                            ModifiedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6900)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6901),
                            FirstName = "Ahmet",
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            ModifiedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6901)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6902),
                            FirstName = "Elif",
                            IsDeleted = false,
                            LastName = "Demirtaş",
                            ModifiedDate = new DateTime(2024, 12, 24, 13, 30, 5, 113, DateTimeKind.Local).AddTicks(6902)
                        });
                });

            modelBuilder.Entity("Survivor.Entities.Competitor", b =>
                {
                    b.HasOne("Survivor.Entities.Category", "Category")
                        .WithMany("Competitors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Survivor.Entities.Category", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
